// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLStorage is a mock of URLStorage interface.
type MockURLStorage struct {
	ctrl     *gomock.Controller
	recorder *MockURLStorageMockRecorder
}

// MockURLStorageMockRecorder is the mock recorder for MockURLStorage.
type MockURLStorageMockRecorder struct {
	mock *MockURLStorage
}

// NewMockURLStorage creates a new mock instance.
func NewMockURLStorage(ctrl *gomock.Controller) *MockURLStorage {
	mock := &MockURLStorage{ctrl: ctrl}
	mock.recorder = &MockURLStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStorage) EXPECT() *MockURLStorageMockRecorder {
	return m.recorder
}

// GetOriginalURL mocks base method.
func (m *MockURLStorage) GetOriginalURL(urlID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", urlID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockURLStorageMockRecorder) GetOriginalURL(urlID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockURLStorage)(nil).GetOriginalURL), urlID)
}

// SaveOriginalURL mocks base method.
func (m *MockURLStorage) SaveOriginalURL(originalURL, generatedID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveOriginalURL", originalURL, generatedID)
}

// SaveOriginalURL indicates an expected call of SaveOriginalURL.
func (mr *MockURLStorageMockRecorder) SaveOriginalURL(originalURL, generatedID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOriginalURL", reflect.TypeOf((*MockURLStorage)(nil).SaveOriginalURL), originalURL, generatedID)
}
